### PR TITLE
Update CatalogItem to type string

### PR DESCRIPTION
**Pull request by splimby**

### CODE REVIEW

**Comment by shnewto** [comment]
@splimby There are a few repercussions to this change / other areas the non-string data structure is used, I think they'll need to be addressed as well for this to fix the issue it's attempting to. I'll list them below.

**Comment by shnewto** [comment]
First, there's another instance of a non-string CatalogItem in `invoiced-go/invdendpoint/subscriptionaddons.go` that may need to be made a string as well. 

Next, the files `invoiced-go/subscriptions.go` and `invoiced-go/invoice.go` are doing some extra work with an `expandValues` function called on `"items.catalog_item"` and `"addons.catalog_item"`  that fails when CatalogItem is a string.

**Comment by shnewto** [comment]
I've taken a stab at testing this all locally and after incorporating your fix _and_ addressing the issues I've outlined above. So far, things seem to be behaving nicely.

**Comment by splimby** [comment]
Okay, cool. If you've got it, perhaps I'll close this PR and you can open one?

**Comment by shnewto** [comment]
@splimby I haven't propagated the changes to the tests yet but I can plan on making a PR with the changes once things are worked out on our end / in our fork. Possibly early next week if that'd work for you?

**Comment by splimby** [comment]
Sure! That sounds great. In the meantime we can communicate as needed by email.

**Comment by shnewto** [comment]
👍

**Pull request closed without merging**
